apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-gcp-network
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-gcp-network
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This configuration provides a foundation to build and operate GCP network resources.
    meta.crossplane.io/readme: |
     This configuration is used for deploying and managing GCP network resources on Kubernetes using Crossplane. This setup provides the necessary infrastructure to deploy GCP network resources managed with Crossplane in Kubernetes. This approach ensures a flexible, streamlined deployment workflow.

     For more details and customization options, you can explore [the GitHub repository](https://github.com/upbound/configuration-app).
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-gcp-compute
      # renovate: datasource=github-releases depName=upbound/provider-gcp
      version: "v0.41.0"
    - function: xpkg.upbound.io/upbound/function-patch-and-transform
      # renovate: datasource=github-releases depName=upbound/function-patch-and-transform
      version: "v0.2.1"
